theme: minima
title: "My Trivia App"
description: "A fun trivia API app with various quiz questions."
url: "https://your-username.github.io/Trivia-API/"
author: "Pravinkumar R"

minima:
  show_excerpts: true  # Example of additional theme options